- hosts: ansible

  tasks:
  - name: create docker image
    command: docker build -t myapp:latest .
    args:
     chdir: /opt/docker

  - name: create tag to push image onto dockerhub
    command: docker tag myapp:latest chydinma/myapp:latest

  - name: push docker image
    command: docker push chydinma/myapp:latest
